window.tyrano_lang = {
    word: {
        go_title: "Return to title. Is that OK?",
        exit_game: "Close the window and exit the game. Is that OK?",
        not_saved: "No saved data is available yet.",
        confirm: "Confirm",
        confirm_beforeunload: "There are unsaved changes. Are you sure you want to exit the game?",
        tag: "Tag",
        not_exists: " does not exist.",
        error: "An error occurred. Please check the script.",
        label: "Label",
        label_double: "is duplicated within the same scenario file.",
        error_occurred: "An error has occurred.",
        save_file_violation_1: "Movement of the save data has been detected. If the save data is untrustworthy, do not load it.",
        save_file_violation_2: "Is it OK to load the save data and start the game?",
        save_file_violation_3: "Launch aborted. Please delete the save data and try starting again.",
        double_start: "The game is already running. Multiple instances cannot be launched.",
        reload: "Reload",
        line: "Line { line }",
        initialized_saved_data: "Save data has been initialized.",
        initializing_saved_data: "Initialize save data. Is that OK?",
        saved_data_is_corrupted: "The save data may be corrupted. Would you like to initialize the save data?",
        save_does_not_work: "The save feature does not work in this environment. This may occur when running locally.",
        undefined_tag: "Tag \"{ name }\" does not exist.",
        undefined_label: "Label \"{ name }\" does not exist.",
        undefined_character: "The specified character \"{ name }\" is not defined. Please define it using [chara_new].",
        undefined_face: "The expression \"{ face }\" for character \"{ name }\" is not defined. Please define it using [chara_face].",
        undefined_character_parts: "The alternate parts for character \"{ name }\" are not defined. Please define them using [chara_layer].",
        undefined_keyframe: "The specified keyframe animation \"{ keyframe }\" is not defined. Please define it using [keyframe].",
        undefined_3d_model: "The specified 3D model \"{ name }\" is not defined.",
        preload_failure_sound:
            "Sound file \"{ src }\" not found. Is the path specified as a full path?\n\n(Example) ./data/bgm/my_bgm.mp3",
        preload_failure_image:
            "Image file \"{ src }\" not found. Is the path specified as a full path?\n\n(Example) ./data/image/my_image.png",
        preload_failure_video:
            "Video file \"{ src }\" not found. Is the path specified as a full path?\n\n(Example) ./data/video/my_video.mp4",
        invalid_keyframe: "The keyframe value is invalid.",
        invalid_keyframe_percentage:
            'The percentage "{ percentage }" set for the keyframe is invalid. Specify it as "0%", "30%", etc.',
        error_in_iscript: "An error occurred within [iscript].",
        missing_endif: "After [if], none of [elsif], [else], or [endif] were found, or there are too many tags inside [if].",
        missing_endmacro: "After [macro], [endmacro] was not found, or there are too many tags inside [macro].",
        missing_endignore: "After [ignore], [endignore] was not found, or there are too many items inside [ignore].",
        missing_parameter: "Parameter \"{ param }\" is required for tag \"{ tag }\".",
        if_and_endif_do_not_match: "The number of [if] and [endif] tags does not match.",
        unsupported_extensions: "\"{ ext }\" is not a supported file format.",
        undefined_keyconfig:
            "Key configuration is not defined. Either KeyConfig.js does not exist or there is a syntax error within it. Please check for missing commas, ']', or '}'.",
        compensate_missing_quart:
            "Unexpected \"]\" detected. The number of quotes in the parameters may be insufficient, so it has been automatically corrected and interpreted.\n\nBefore: { before }\nAfter: { after }",
        duplicate_label:
            "Label \"{ name }\" is duplicated within the same scenario file. Please ensure that label names are unique within the file.",
        file_not_found: "File not found.\n\n{ path }",
        patch_not_found: "Patch file not found.\n\n{ path }",
        new_patch_found: "A new update has been found.\n\nVer: { version }\n{ message }\n\nWould you like to apply the update?",
        apply_web_patch: "The update will be applied. After completion, the game will automatically exit.",
        apply_patch_complete: "The update has been applied. Please restart the game.",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
        error_occurred: "error occurred",
    },
};
